[package]
name = "telecom"
version = "0.1.0"
authors = ["Valdemar Erk <valdemar@erk.io>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
telecom-sys = { version = "0.1", path = "./../telecom-sys" }